apiVersion: v1
kind: Service
metadata:
  name: realworld-htmx-service
spec:
  selector:
    app: realworld-htmx
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32101
  type: NodePort